app:
  name: "Stock Market Trend Prediction System"
  version: "1.0.0"
  debug: true

data:
  default_ticker: "RELIANCE.NS"
  default_period: "1y"
  cache_duration: 3600

models:
  default_model: "random_forest"
  available_models: ["random_forest", "xgboost", "lstm"]
  train_test_split: 0.8
  random_state: 42

technical_indicators:
  sma_periods: [20, 50, 200]
  ema_periods: [12, 26]
  rsi_period: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  bb_period: 20
  bb_std: 2

ui:
  theme: "light"
  chart_height: 600